from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Preformatted
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
import re
import html
import os

styles = getSampleStyleSheet()
if "Code" not in styles:
    styles.add(ParagraphStyle(
        name="Code", fontName="Courier", fontSize=10, leading=14,
        textColor=colors.black, backColor=colors.whitesmoke,
        leftIndent=10, rightIndent=10, spaceBefore=10, spaceAfter=10
    ))

def safe_filename(text: str) -> str:
    text = re.sub(r'[^a-zA-Z0-9_\w\s-]', ' ', text)
    return text.strip().replace(" ", "_")[:50]

def clean_text_for_pdf(text: str) -> str:
    text = re.sub(r'\*\*(.*?)\*\*', r'\1', text)
    text = re.sub(r'\*(.*?)\*', r'\1', text)
    text = text.replace("* ", "• ")
    text = html.escape(text)
    return text.replace("\n", "<br/>")

def parse_answer(answer: str):
    parts = []
    segments = re.split(r'```(?:\w+)?\n?(.*?)```', answer, flags=re.DOTALL)
    for i, segment in enumerate(segments):
        if segment.strip():
            parts.append({"type": "text" if i % 2 == 0 else "code", "content": segment.strip()})
    if not parts:
        parts.append({"type": "text", "content": answer.strip()})
    return parts

def generate_pdf(question: str, answer: str, marks: int):
    os.makedirs("uploads/pdfs", exist_ok=True)
    file_name = f"uploads/pdfs/{safe_filename(question)}.pdf"
    doc = SimpleDocTemplate(file_name, pagesize=A4, rightMargin=50, leftMargin=50, topMargin=60, bottomMargin=60)
    content = []
    content.append(Paragraph("SkillForge AI - Answer Sheet", styles["Title"]))
    content.append(Spacer(1, 16))
    content.append(Paragraph(f"<b>Question ({marks} marks):</b> {html.escape(question)}", styles["Normal"]))
    content.append(Spacer(1, 16))
    content.append(Paragraph("<b>Answer:</b>", styles["Normal"]))
    content.append(Spacer(1, 8))
    
    for part in parse_answer(answer):
        if part["type"] == "text":
            for para in part["content"].split("\n\n"):
                if para.strip():
                    content.append(Paragraph(clean_text_for_pdf(para.strip()), styles["Normal"]))
                    content.append(Spacer(1, 6))
        else:
            content.append(Spacer(1, 6))
            content.append(Preformatted(part["content"], styles["Code"]))
            content.append(Spacer(1, 6))
            
    content.append(Spacer(1, 20))
    content.append(Paragraph("<i>Generated by SkillForge AI</i>", styles["Normal"]))
    doc.build(content)
    return file_name