from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Preformatted
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
import re
import html
import os

styles = getSampleStyleSheet()

if "Code" not in styles:
    styles.add(
        ParagraphStyle(
            name="Code",
            fontName="Courier",
            fontSize=10,
            leading=14,
            textColor=colors.black,
            backColor=colors.whitesmoke,
            leftIndent=10,
            rightIndent=10,
            spaceBefore=10,
            spaceAfter=10,
        )
    )

def safe_filename(text: str) -> str:
    text = re.sub(r'[^a-zA-Z0-9_\w\s-]', ' ', text)
    text = text.strip().replace(" ", "_")
    return text[:50]

def clean_text_for_pdf(text: str) -> str:
    text = re.sub(r'\*\*(.*?)\*\*', r'\1', text)
    text = re.sub(r'\*(.*?)\*', r'\1', text)
    text = text.replace("* ", "• ")
    text = html.escape(text)
    text = text.replace("\n", "<br/>")
    return text

def parse_answer(answer: str):
    parts = []
    # split on triple backtick code blocks
    segments = re.split(r'```(?:\w+)?\n?(.*?)```', answer, flags=re.DOTALL)

    for i, segment in enumerate(segments):
        if segment.strip():
            if i % 2 == 0:
                # text section
                parts.append({"type": "text", "content": segment.strip()})
            else:
                # code block
                parts.append({"type": "code", "content": segment.strip()})

    # if nothing found just return whole answer as text
    if not parts:
        parts.append({"type": "text", "content": answer.strip()})

    return parts

def generate_pdf(question: str, answer: str, marks: int):
    os.makedirs("backend/uploads/pdfs", exist_ok=True)
    file_name = f"backend/uploads/pdfs/{safe_filename(question)}.pdf"

    doc = SimpleDocTemplate(
        file_name,
        pagesize=A4,
        rightMargin=50,
        leftMargin=50,
        topMargin=60,
        bottomMargin=60
    )

    content = []

    # Title
    content.append(Paragraph("SkillForge AI - Answer Sheet", styles["Title"]))
    content.append(Spacer(1, 16))

    # Question
    content.append(Paragraph(f"<b>Question ({marks} marks):</b>", styles["Normal"]))
    content.append(Spacer(1, 6))
    content.append(Paragraph(html.escape(question), styles["Normal"]))
    content.append(Spacer(1, 16))

    # Answer label
    content.append(Paragraph("<b>Answer:</b>", styles["Normal"]))
    content.append(Spacer(1, 8))

    # Parse and add all parts
    parts = parse_answer(answer)

    for part in parts:
        if part["type"] == "text":
            paragraphs = part["content"].split("\n\n")
            for para in paragraphs:
                if para.strip():
                    cleaned = clean_text_for_pdf(para.strip())
                    content.append(Paragraph(cleaned, styles["Normal"]))
                    content.append(Spacer(1, 6))

        elif part["type"] == "code":
            content.append(Spacer(1, 6))
            content.append(Preformatted(part["content"], styles["Code"]))
            content.append(Spacer(1, 6))

    # Footer
    content.append(Spacer(1, 20))
    content.append(Paragraph(
        "<i>Generated by SkillForge AI - Your personal coding buddy</i>",
        styles["Normal"]
    ))

    doc.build(content)
    return file_name